import { defineConfig } from "vite";
import { resolve } from "path";

// ── Library build configuration ───────────────────────────────────────────────
//
//   npm run build:lib
//
// Produces:
//   dist/lib/index.{js,cjs}         — main entry
//   dist/lib/island/index.{js,cjs}  — island subpath
//   dist/lib/**/*.d.ts              — Type declarations (generated by tsc)

export default defineConfig({
    publicDir: false,

    build: {
        outDir: "dist/lib",
        emptyOutDir: true,
        sourcemap: true,

        lib: {
            entry: {
                index: resolve("src/index.ts"),
                "island/index": resolve("src/island/index.ts"),
            },
            name: "NixJSKit",
            formats: ["es", "cjs"],
            fileName: (format, entryName) =>
                format === "cjs"
                    ? `${entryName}.cjs`
                    : `${entryName}.js`,
        },

        rollupOptions: {
            external: ["@deijose/nix-js", "happy-dom"],
            output: {
                preserveModules: false,
                globals: {
                    "@deijose/nix-js": "NixJS",
                    "happy-dom": "HappyDOM",
                },
            },
        },
    },
});
