import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { scanRoutes } from "../router/route-scanner";
import type { Adapter } from "./index";
import { writeSsrEntry } from "./shared";

/**
 * Bun adapter for nix-js-kit.
 *
 * Produces a self-contained Bun server entry at `.nix-js/bun-server.ts`.
 * Run it with:
 *
 *   bun run .nix-js/bun-server.ts
 *
 * The server serves static files from `dist/` and renders pages on demand for
 * unmatched routes.
 */
export const bunAdapter: Adapter = {
  name: "bun",

  async build(options) {
    const root = resolve(options.root);
    const outDir = resolve(root, options.outDir);
    const generatedDir = resolve(root, ".nix-js");

    // Verify the production build exists.
    try {
      await stat(outDir);
    } catch {
      throw new Error(
        `Output directory not found: ${outDir}. Run "nix-js-kit build" first.`,
      );
    }

    // Clean previous adapter output.
    await rm(generatedDir, { recursive: true, force: true });
    await mkdir(generatedDir, { recursive: true });

    // Scan routes and generate a self-contained SSR handler entry.
    const appDir = resolve(root, options.appDir);
    const routes = await scanRoutes(appDir);

    const entryPath = resolve(generatedDir, "bun-index.ts");
    await writeSsrEntry(entryPath, routes, options, appDir);

    // Write the Bun server entry.
    const serverPath = resolve(generatedDir, "bun-server.ts");
    await writeFile(
      serverPath,
      buildBunServerSource(outDir, options),
      "utf8",
    );
  },
};

function buildBunServerSource(
  outDir: string,
  options: {
    clientEntry: string;
    lang: string;
    port?: number;
  },
): string {
  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { stat } from "node:fs/promises";
import { join } from "node:path";
import handler from "./bun-index.ts";

const outDir = ${JSON.stringify(outDir)};
const port = Number(process.env.PORT) || ${options.port ?? 3000};

async function serveStatic(request: Request): Promise<Response | null> {
  const url = new URL(request.url);
  let filePath = join(outDir, url.pathname);
  if (url.pathname.endsWith("/")) {
    filePath = join(filePath, "index.html");
  }
  try {
    const s = await stat(filePath);
    if (s.isFile()) {
      return new Response(Bun.file(filePath));
    }
  } catch {
    // fall through to SSR
  }
  return null;
}

Bun.serve({
  port,
  async fetch(request) {
    const staticResponse = await serveStatic(request);
    if (staticResponse) return staticResponse;
    return handler(request);
  },
});

console.log(\`Bun server running at http://localhost:\${port}\`);
`;
}
