import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "vite";
import { scanRoutes } from "../router/route-scanner";
import type { Adapter } from "./index";
import { writeSsrEntry } from "./shared";

/**
 * Node adapter for nix-js-kit.
 *
 * Produces a self-contained Node server entry at `.nix-js/node-server.mjs`.
 * Run it with:
 *
 *   node .nix-js/node-server.mjs
 *
 * The server serves static files from `dist/` and renders pages on demand for
 * unmatched routes.
 */
export const nodeAdapter: Adapter = {
  name: "node",

  async build(options) {
    const root = resolve(options.root);
    const outDir = resolve(root, options.outDir);
    const generatedDir = resolve(root, ".nix-js");

    try {
      await stat(outDir);
    } catch {
      throw new Error(
        `Output directory not found: ${outDir}. Run "nix-js-kit build" first.`,
      );
    }

    await rm(generatedDir, { recursive: true, force: true });
    await mkdir(generatedDir, { recursive: true });

    const appDir = resolve(root, options.appDir);
    const routes = await scanRoutes(appDir);

    const entryPath = resolve(generatedDir, "node-index.ts");
    await writeSsrEntry(entryPath, routes, options, appDir);

    const serverPath = resolve(generatedDir, "node-server.ts");
    await writeFile(
      serverPath,
      buildNodeServerSource(outDir, options),
      "utf8",
    );

    await build({
      configFile: false,
      root,
      build: {
        outDir: generatedDir,
        emptyOutDir: false,
        ssr: true,
        lib: {
          entry: serverPath,
          formats: ["es"],
        },
        rollupOptions: {
          external: [],
          output: {
            entryFileNames: "node-server.mjs",
            inlineDynamicImports: true,
          },
        },
      },
    });
  },
};

function buildNodeServerSource(
  outDir: string,
  options: {
    clientEntry: string;
    lang: string;
    port?: number;
  },
): string {
  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { createServer, type IncomingMessage } from "node:http";
import { readFile, stat } from "node:fs/promises";
import { extname, join } from "node:path";
import handler from "./node-index.ts";

const outDir = ${JSON.stringify(outDir)};
const port = Number(process.env.PORT) || ${options.port ?? 3000};

async function serveStatic(request: Request): Promise<Response | null> {
  const url = new URL(request.url);
  let filePath = join(outDir, url.pathname);
  if (url.pathname.endsWith("/")) {
    filePath = join(filePath, "index.html");
  }
  try {
    const s = await stat(filePath);
    if (!s.isFile()) return null;
    const data = await readFile(filePath);
    return new Response(data, { headers: { "Content-Type": guessContentType(filePath) } });
  } catch {
    return null;
  }
}

function guessContentType(filePath: string): string {
  switch (extname(filePath)) {
    case ".html": return "text/html; charset=utf-8";
    case ".js":
    case ".mjs": return "application/javascript; charset=utf-8";
    case ".css": return "text/css; charset=utf-8";
    case ".json": return "application/json; charset=utf-8";
    case ".svg": return "image/svg+xml";
    case ".png": return "image/png";
    case ".jpg":
    case ".jpeg": return "image/jpeg";
    default: return "application/octet-stream";
  }
}

function readBody(req: IncomingMessage): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

createServer(async (req, res) => {
  const url = \`http://\${req.headers.host || "localhost"}\${req.url}\`;
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      for (const v of value) headers.append(key, v);
    } else {
      headers.set(key, value);
    }
  }

  let body: Buffer | undefined;
  if (req.method !== "GET" && req.method !== "HEAD") {
    body = await readBody(req);
  }

  const request = new Request(url, { method: req.method, headers, body });
  const staticResponse = await serveStatic(request);
  const response = staticResponse ?? await handler(request);

  res.writeHead(response.status, Object.fromEntries(response.headers.entries()));
  res.end(Buffer.from(await response.arrayBuffer()));
}).listen(port, () => {
  console.log(\`Node server running at http://localhost:\${port}\`);
});
`;
}
