import { mkdir, readdir, copyFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { scanRoutes } from "../router/route-scanner";
import type { AdapterOptions } from "./index";
import type { PageRoute } from "../router/route-scanner";

/**
 * Shared helper: copy a directory recursively.
 */
export async function copyStatic(from: string, to: string): Promise<void> {
  await mkdir(to, { recursive: true });
  const entries = await readdir(from, { withFileTypes: true });
  for (const entry of entries) {
    const src = join(from, entry.name);
    const dest = join(to, entry.name);
    if (entry.isDirectory()) {
      await copyStatic(src, dest);
    } else {
      await copyFile(src, dest);
    }
  }
}

/**
 * Build a self-contained SSR entry file for a platform adapter.
 * The generated module exports a default `handler(request: Request): Response`
 * and keeps a registry of all page/layout/data/action modules so the runtime
 * can import them synchronously after bundling.
 */
export function buildSsrEntry(
  routes: Awaited<ReturnType<typeof scanRoutes>>,
  options: AdapterOptions,
  appDir: string,
  entryDir: string,
): string {
  // Collect all module paths that the SSR runtime may need to import.
  const moduleSet = new Set<string>();
  const actionPaths = new Set<string>();
  for (const page of routes.pages) {
    collectPageModules(page, moduleSet, actionPaths);
  }
  if (routes.error404) collectPageModules(routes.error404, moduleSet, actionPaths);
  if (routes.error500) collectPageModules(routes.error500, moduleSet, actionPaths);
  const modules = Array.from(moduleSet);
  const moduleIndex = new Map(modules.map((path, index) => [path, index]));

  const imports = modules
    .map((path, index) => {
      const rel = relativeToPosix(entryDir, path);
      return `import * as m_${index} from ${JSON.stringify(rel)};`;
    })
    .join("\n");

  const actionModules = Array.from(actionPaths)
    .map((path) => {
      const index = moduleIndex.get(path);
      return `  [${JSON.stringify(path)}, m_${index}],`;
    })
    .join("\n");

  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { handleActionRequest, matchRoute, renderPage, renderErrorPage, scanRoutes } from "@deijose/nix-js-kit";
${imports}

const registry = new Map<string, unknown>([
${modules.map((path, index) => `  [${JSON.stringify(path)}, m_${index}],`).join("\n")}
]);

const actionModules = new Map<string, unknown>([
${actionModules}
]);

const appDir = ${JSON.stringify(appDir)};
const clientEntry = ${JSON.stringify(options.clientEntry)};
const lang = ${JSON.stringify(options.lang)};

let routesPromise: Promise<ReturnType<typeof scanRoutes>> | null = null;
async function getRoutes() {
  if (!routesPromise) routesPromise = scanRoutes(appDir);
  return routesPromise;
}

async function loadModule(path: string) {
  const mod = registry.get(path);
  if (mod) return mod;
  throw new Error(\`Module not found in registry: \${path}\`);
}

async function resolveAction(name: string) {
  for (const [, mod] of actionModules) {
    const action = (mod as Record<string, unknown>)[name];
    if (typeof action === "function") {
      return action as (...args: unknown[]) => unknown;
    }
  }
}

export default async function handler(request: Request): Promise<Response> {
  const url = new URL(request.url);

  if (url.pathname === "/__nix-js/actions") {
    return handleActionRequest(request, resolveAction);
  }

  const routes = await getRoutes();
  const match = matchRoute(url.pathname, routes.pages);

  if (!match) {
    const errorResult = await renderErrorPage({ routes, status: 404, config: { lang, clientEntry }, importer: loadModule });
    if (errorResult) {
      return new Response(errorResult.html, { status: errorResult.status, headers: { "Content-Type": "text/html; charset=utf-8" } });
    }
    return new Response("Not Found", { status: 404, headers: { "Content-Type": "text/plain" } });
  }

  try {
    const html = await renderPage({
      route: match.route,
      params: match.params,
      searchParams: match.searchParams,
      config: { lang, clientEntry },
      importer: loadModule,
    });
    return new Response(html, { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } });
  } catch (err) {
    console.error("[nix-js-kit] SSR render error:", err);
    const errorResult = await renderErrorPage({ routes, status: 500, error: err, config: { lang, clientEntry }, importer: loadModule });
    if (errorResult) {
      return new Response(errorResult.html, { status: errorResult.status, headers: { "Content-Type": "text/html; charset=utf-8" } });
    }
    return new Response(String(err), { status: 500, headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }
}
`;
}

function relativeToPosix(from: string, to: string): string {
  return relative(from, to).split("\\").join("/");
}

function collectPageModules(
  page: PageRoute,
  moduleSet: Set<string>,
  actionPaths: Set<string>,
): void {
  moduleSet.add(page.pagePath);
  if (page.dataPath) moduleSet.add(page.dataPath);
  for (const layout of page.layouts) moduleSet.add(layout);
  if (page.actionPath) {
    moduleSet.add(page.actionPath);
    actionPaths.add(page.actionPath);
  }
}

/**
 * Write a generated SSR entry file for an adapter.
 */
export async function writeSsrEntry(
  entryPath: string,
  routes: Awaited<ReturnType<typeof scanRoutes>>,
  options: AdapterOptions,
  appDir: string,
): Promise<void> {
  await writeFile(
    entryPath,
    buildSsrEntry(routes, options, appDir, dirname(entryPath)),
    "utf8",
  );
}
