import { mkdir, readdir, copyFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { scanRoutes } from "../router/route-scanner";
import type { AdapterOptions } from "./index";
import type { PageRoute } from "../router/route-scanner";

/**
 * Shared helper: copy a directory recursively.
 */
export async function copyStatic(from: string, to: string): Promise<void> {
  await mkdir(to, { recursive: true });
  const entries = await readdir(from, { withFileTypes: true });
  for (const entry of entries) {
    const src = join(from, entry.name);
    const dest = join(to, entry.name);
    if (entry.isDirectory()) {
      await copyStatic(src, dest);
    } else {
      await copyFile(src, dest);
    }
  }
}

/**
 * Build a self-contained SSR entry file for a platform adapter.
 * The generated module exports a default `handler(request: Request): Response`
 * and keeps a registry of all page/layout/data/action modules so the runtime
 * can import them synchronously after bundling.
 */
export async function buildSsrEntry(
  routes: Awaited<ReturnType<typeof scanRoutes>>,
  options: AdapterOptions,
  appDir: string,
  entryDir: string,
): Promise<string> {
  // Collect all module paths that the SSR runtime may need to import.
  const moduleSet = new Set<string>();
  const actionPathsByPage = new Map<string, Set<string>>();
  for (const page of routes.pages) {
    collectPageModules(page, moduleSet, actionPathsByPage);
  }
  if (routes.error404) collectPageModules(routes.error404, moduleSet, actionPathsByPage);
  if (routes.error500) collectPageModules(routes.error500, moduleSet, actionPathsByPage);
  for (const api of routes.api) {
    moduleSet.add(api.routePath);
  }
  const modules = Array.from(moduleSet);
  const moduleIndex = new Map(modules.map((path, index) => [path, index]));

  const imports = modules
    .map((path, index) => {
      const rel = relativeToPosix(entryDir, path);
      return `import * as m_${index} from ${JSON.stringify(rel)};`;
    })
    .join("\n");

  const actionModules = Array.from(actionPathsByPage.entries())
    .map(([pagePath, paths]) => {
      const entries = Array.from(paths)
        .map((path) => {
          const index = moduleIndex.get(path);
          return `      [${JSON.stringify(path)}, m_${index}],`;
        })
        .join("\n");
      return `  [${JSON.stringify(pagePath)}, new Map([\n${entries}\n    ])],`;
    })
    .join("\n");

  const actionsRegistry: Record<string, Record<string, string>> = {};
  for (const page of routes.pages) {
    if (!page.actionPath) continue;
    const mod = (await import(page.actionPath)) as Record<string, unknown>;
    const names: Record<string, string> = {};
    for (const [name, value] of Object.entries(mod)) {
      if (name === "default") continue;
      if (typeof value === "function") {
        names[name] = page.actionPath;
      }
    }
    if (Object.keys(names).length > 0) {
      actionsRegistry[page.path] = names;
    }
  }

  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { handleActionRequest, matchApiRoute, matchRoute, renderPage, renderErrorPage, scanRoutes } from "@deijose/nix-js-kit";
${imports}

const registry = new Map<string, unknown>([
${modules.map((path, index) => `  [${JSON.stringify(path)}, m_${index}],`).join("\n")}
]);

const apiRoutes = [
${routes.api.map((api) => {
    const index = moduleIndex.get(api.routePath);
    return `  { path: ${JSON.stringify(api.path)}, routePath: m_${index} },`;
  }).join("\n")}
];

const actionModules = new Map<string, Map<string, unknown>>([
${actionModules}
]);

const actions = ${JSON.stringify(actionsRegistry)};

const appDir = ${JSON.stringify(appDir)};
const clientEntry = ${JSON.stringify(options.clientEntry)};
const lang = ${JSON.stringify(options.lang)};

let routesPromise: Promise<ReturnType<typeof scanRoutes>> | null = null;
async function getRoutes() {
  if (!routesPromise) routesPromise = scanRoutes(appDir);
  return routesPromise;
}

async function loadModule(path: string) {
  const mod = registry.get(path);
  if (mod) return mod;
  throw new Error(\`Module not found in registry: \${path}\`);
}

async function resolveAction(name: string, page?: string) {
  const pageModules = page ? actionModules.get(page) : undefined;
  if (pageModules) {
    const mod = pageModules.get(name);
    if (mod) {
      const action = (mod as Record<string, unknown>)[name];
      if (typeof action === "function") {
        return action as (...args: unknown[]) => unknown;
      }
    }
  }
  for (const [, mods] of actionModules) {
    const mod = mods.get(name);
    if (mod) {
      const action = (mod as Record<string, unknown>)[name];
      if (typeof action === "function") {
        return action as (...args: unknown[]) => unknown;
      }
    }
  }
}

export default async function handler(request: Request): Promise<Response> {
  const url = new URL(request.url);

  if (url.pathname === "/__nix-js/actions") {
    return handleActionRequest(request, resolveAction);
  }

  const apiMatch = matchApiRoute(url.pathname, apiRoutes);
  if (apiMatch) {
    const mod = apiMatch.route.routePath as Record<string, (request: Request) => unknown>;
    const handler = mod[request.method ?? "GET"];
    if (typeof handler !== "function") {
      return new Response("Method not allowed: " + request.method, { status: 405, headers: { "Content-Type": "text/plain" } });
    }
    return (await handler(request)) as Response;
  }

  const routes = await getRoutes();
  const match = matchRoute(url.pathname, routes.pages);

  if (!match) {
    const errorResult = await renderErrorPage({ routes, status: 404, config: { lang, clientEntry }, actions, importer: loadModule });
    if (errorResult) {
      return new Response(errorResult.html, { status: errorResult.status, headers: { "Content-Type": "text/html; charset=utf-8" } });
    }
    return new Response("Not Found", { status: 404, headers: { "Content-Type": "text/plain" } });
  }

  try {
    const html = await renderPage({
      route: match.route,
      params: match.params,
      searchParams: match.searchParams,
      config: { lang, clientEntry },
      importer: loadModule,
      actions,
    });
    return new Response(html, { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } });
  } catch (err) {
    console.error("[nix-js-kit] SSR render error:", err);
    const errorResult = await renderErrorPage({ routes, status: 500, error: err, config: { lang, clientEntry }, actions, importer: loadModule });
    if (errorResult) {
      return new Response(errorResult.html, { status: errorResult.status, headers: { "Content-Type": "text/html; charset=utf-8" } });
    }
    return new Response(String(err), { status: 500, headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }
}
`;
}

function relativeToPosix(from: string, to: string): string {
  return relative(from, to).split("\\").join("/");
}

function collectPageModules(
  page: PageRoute,
  moduleSet: Set<string>,
  actionPathsByPage: Map<string, Set<string>>,
): void {
  moduleSet.add(page.pagePath);
  if (page.dataPath) moduleSet.add(page.dataPath);
  if (page.loadingPath) moduleSet.add(page.loadingPath);
  for (const layout of page.layouts) moduleSet.add(layout);
  if (page.actionPath) {
    moduleSet.add(page.actionPath);
    let set = actionPathsByPage.get(page.path);
    if (!set) {
      set = new Set<string>();
      actionPathsByPage.set(page.path, set);
    }
    set.add(page.actionPath);
  }
}

/**
 * Write a generated SSR entry file for an adapter.
 */
export async function writeSsrEntry(
  entryPath: string,
  routes: Awaited<ReturnType<typeof scanRoutes>>,
  options: AdapterOptions,
  appDir: string,
): Promise<void> {
  await writeFile(
    entryPath,
    await buildSsrEntry(routes, options, appDir, dirname(entryPath)),
    "utf8",
  );
}
