import {
  mkdir,
  readdir,
  copyFile,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { build } from "vite";
import { scanRoutes } from "../router/route-scanner";
import type { Adapter, AdapterOptions } from "./index";

/**
 * Vercel adapter for nix-js-kit.
 *
 * Produces a `.vercel/output` directory compatible with the Vercel Build Output
 * API (v3). Static files are served from `dist/` and unmatched routes fall back
 * to the SSR function.
 */
export const vercelAdapter: Adapter = {
  name: "vercel",

  async build(options) {
    const root = resolve(options.root);
    const outDir = resolve(root, options.outDir);
    const vercelOut = resolve(root, ".vercel/output");
    const functionsDir = join(vercelOut, "functions", "__nix-kit.func");
    const generatedDir = resolve(root, ".nix-js");

    // Verify the production build exists.
    try {
      await stat(outDir);
    } catch {
      throw new Error(
        `Output directory not found: ${outDir}. Run "nix-js-kit build" first.`,
      );
    }

    // Clean previous adapter output.
    await rm(vercelOut, { recursive: true, force: true });
    await mkdir(vercelOut, { recursive: true });
    await mkdir(functionsDir, { recursive: true });
    await mkdir(generatedDir, { recursive: true });

    // Copy static files.
    await copyStatic(outDir, join(vercelOut, "static"));

    // Scan routes and generate a self-contained function entry.
    const appDir = resolve(root, options.appDir);
    const routes = await scanRoutes(appDir);

    const entryPath = resolve(generatedDir, "vercel-index.ts");
    await writeFile(
      entryPath,
      buildVercelEntry(routes, options, appDir, generatedDir),
      "utf8",
    );

    // Bundle the function entry.
    await build({
      configFile: false,
      root,
      build: {
        outDir: functionsDir,
        emptyOutDir: true,
        ssr: true,
        lib: {
          entry: entryPath,
          formats: ["es"],
          fileName: () => "index.js",
        },
        rollupOptions: {
          external: [],
          output: {
            inlineDynamicImports: true,
          },
        },
      },
    });

    // Vite SSR lib builds may use the entry file name, so force the expected handler name.
    const generatedHandler = join(functionsDir, "vercel-index.js");
    const targetHandler = join(functionsDir, "index.js");
    try {
      await stat(generatedHandler);
      await rename(generatedHandler, targetHandler);
    } catch {
      // If the file is already named index.js, nothing to do.
    }

    // Write Vercel function config.
    await writeFile(
      join(functionsDir, ".vc-config.json"),
      JSON.stringify(
        {
          runtime: "nodejs20.x",
          handler: "index.js",
          launcherType: "Nodejs",
          shouldAddHelpers: true,
        },
        null,
        2,
      ),
      "utf8",
    );

    // Write Vercel root config.
    await writeFile(
      join(vercelOut, "config.json"),
      JSON.stringify(
        {
          version: 3,
          routes: [
            { handle: "filesystem" },
            { src: "/(.*)", "dest": "/__nix-kit" },
          ],
        },
        null,
        2,
      ),
      "utf8",
    );
  },
};

async function copyStatic(from: string, to: string): Promise<void> {
  await mkdir(to, { recursive: true });
  const entries = await readdir(from, { withFileTypes: true });
  for (const entry of entries) {
    const src = join(from, entry.name);
    const dest = join(to, entry.name);
    if (entry.isDirectory()) {
      await copyStatic(src, dest);
    } else {
      await copyFile(src, dest);
    }
  }
}

function buildVercelEntry(
  routes: Awaited<ReturnType<typeof scanRoutes>>,
  options: AdapterOptions,
  appDir: string,
  entryDir: string,
): string {
  // Collect all module paths that the SSR runtime may need to import.
  const moduleSet = new Set<string>();
  for (const page of routes.pages) {
    moduleSet.add(page.pagePath);
    if (page.dataPath) moduleSet.add(page.dataPath);
    for (const layout of page.layouts) moduleSet.add(layout);
  }
  const modules = Array.from(moduleSet);

  const imports = modules
    .map((path, index) => {
      const rel = relativeToPosix(entryDir, path);
      return `import * as m_${index} from ${JSON.stringify(rel)};`;
    })
    .join("\n");

  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { matchRoute, renderPage, scanRoutes } from "@deijose/nix-js-kit";
${imports}

const registry = new Map<string, unknown>([
${modules.map((path, index) => `  [${JSON.stringify(path)}, m_${index}],`).join("\n")}
]);

const appDir = ${JSON.stringify(appDir)};
const clientEntry = ${JSON.stringify(options.clientEntry)};
const lang = ${JSON.stringify(options.lang)};

let routesPromise: Promise<ReturnType<typeof scanRoutes>> | null = null;
async function getRoutes() {
  if (!routesPromise) routesPromise = scanRoutes(appDir);
  return routesPromise;
}

async function loadModule(path: string) {
  const mod = registry.get(path);
  if (mod) return mod;
  throw new Error(\`Module not found in registry: \${path}\`);
}

export default async function handler(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const routes = await getRoutes();
  const match = matchRoute(url.pathname, routes.pages);

  if (!match) {
    return new Response("Not Found", { status: 404, headers: { "Content-Type": "text/plain" } });
  }

  try {
    const html = await renderPage({
      route: match.route,
      params: match.params,
      searchParams: match.searchParams,
      config: { lang, clientEntry },
      importer: loadModule,
    });
    return new Response(html, { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } });
  } catch (err) {
    console.error("[nix-js-kit] SSR render error:", err);
    return new Response(String(err), { status: 500, headers: { "Content-Type": "text/plain; charset=utf-8" } });
  }
}
`;
}

function relativeToPosix(from: string, to: string): string {
  return relative(from, to).split("\\").join("/");
}
