import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, sep } from "node:path";
import type { IslandModule } from "./scan";

// =============================================================================
// --- Client entry generator ---
// =============================================================================
//
// Turns a list of scanned islands into a client entry module that imports each
// island and registers it with `hydrateIslands`. This removes the need to hand-
// maintain `entry-client.ts` as islands are added or removed.
//
// The generated file imports island default exports and passes them to
// `hydrateIslands` keyed by their registry name.
// =============================================================================

/** Options for generating the client entry module. */
export interface GenerateEntryOptions {
  /** Islands to register, from `scanIslands`. */
  islands: IslandModule[];
  /** Absolute path of the entry file to write (e.g. ".nix-js/entry-client.ts"). */
  outFile: string;
  /**
   * Import specifier for the kit's client island helpers.
   * Defaults to the published subpath `@deijose/nix-js-kit/island`.
   */
  hydrateImport?: string;
}

/** Turns a registry name into a safe JS identifier for the import binding. */
function toIdentifier(name: string, index: number): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(cleaned) ? `${cleaned}_${index}` : `_${cleaned}_${index}`;
}

/** Builds the source code of the client entry module. */
export function buildEntrySource(
  islands: IslandModule[],
  outFile: string,
  hydrateImport = "@deijose/nix-js-kit/island",
): string {
  const bindings = islands.map((island, i) => ({
    ident: toIdentifier(island.name, i),
    name: island.name,
    // Relative import specifier from the entry file to the island module.
    spec: toImportSpecifier(outFile, island.filePath),
  }));

  const importLines = bindings
    .map((b) => `import ${b.ident} from "${b.spec}";`)
    .join("\n");

  const registryLines = bindings
    .map((b) => `  ${JSON.stringify(b.name)}: ${b.ident},`)
    .join("\n");

  return `// AUTO-GENERATED by @deijose/nix-js-kit. Do not edit.
import { hydrateIslands } from ${JSON.stringify(hydrateImport)};
${importLines}

hydrateIslands({
${registryLines}
});
`;
}

/** Computes a POSIX-style relative import specifier between two files. */
function toImportSpecifier(fromFile: string, toFile: string): string {
  let spec = relative(dirname(fromFile), toFile).split(sep).join("/");
  if (!spec.startsWith(".")) spec = `./${spec}`;
  return spec;
}

/**
 * Generates and writes the client entry module for the given islands.
 *
 * @param options Generation options.
 * @returns The absolute path of the written entry file.
 */
export async function generateClientEntry(
  options: GenerateEntryOptions,
): Promise<string> {
  const source = buildEntrySource(
    options.islands,
    options.outFile,
    options.hydrateImport,
  );
  await mkdir(dirname(options.outFile), { recursive: true });
  await writeFile(options.outFile, source, "utf8");
  return options.outFile;
}
